import { db } from './firebase.js';
import { collection, getDocs } from 'https://www.gstatic.com/firebasejs/10.12.0/firebase-firestore.js';
const WPP_NUMBER='556193166448', grid=document.getElementById('produtos-grid'), filtros=document.querySelectorAll('.filtro-btn');
const lightbox=document.getElementById('lightbox'), lbImg=document.getElementById('lightbox-img'), lbClose=document.getElementById('lightbox-close'), lbPrev=document.getElementById('lightbox-prev'), lbNext=document.getElementById('lightbox-next'), lbCount=document.getElementById('lightbox-count');
let produtos=[], galeria=[], imagemAtual=0;
document.addEventListener('DOMContentLoaded', async()=>{ await carregar(); filtros.forEach(b=>b.addEventListener('click',()=>{filtros.forEach(x=>x.classList.remove('ativo'));b.classList.add('ativo');renderizar(b.dataset.cat==='todos'?produtos:produtos.filter(p=>p.categoria===b.dataset.cat));})); lbClose?.addEventListener('click',fechar); lightbox?.addEventListener('click',e=>{if(e.target===lightbox)fechar();}); lbPrev?.addEventListener('click',()=>mostrarImagem(imagemAtual-1)); lbNext?.addEventListener('click',()=>mostrarImagem(imagemAtual+1)); document.addEventListener('keydown',e=>{if(e.key==='Escape')fechar();if(lightbox?.classList.contains('aberto')&&e.key==='ArrowLeft')mostrarImagem(imagemAtual-1);if(lightbox?.classList.contains('aberto')&&e.key==='ArrowRight')mostrarImagem(imagemAtual+1);}); });
async function carregar(){grid.innerHTML='<div class="produtos-grid--loading"><div class="spinner"></div></div>';try{const s=await getDocs(collection(db,'produtos'));produtos=s.docs.map(d=>({id:d.id,...d.data()})).filter(p=>p.disponivel===true).sort((a,b)=>(a.ordem??0)-(b.ordem??0));renderizar(produtos);}catch(e){console.error(e);grid.innerHTML='<p class="catalogo-erro">Não foi possível carregar o catálogo. Tente novamente em instantes.</p>';}}
function renderizar(lista){if(!lista.length){grid.innerHTML='<p class="catalogo-erro">Nenhum produto nesta categoria no momento. ♥</p>';return;}grid.innerHTML=lista.map(card).join('');grid.querySelectorAll('[data-carrossel]').forEach(iniciarCarrossel);}
function card(p){const imgs=imagens(p), nome=esc(p.nome), slides=imgs.map((u,i)=>`<img class="produto-card__slide ${i?'':'ativa'}" src="${esc(u)}" alt="${nome}" loading="lazy">`).join('');const nav=imgs.length>1?`<button class="produto-card__nav produto-card__nav--anterior" type="button" aria-label="Imagem anterior">‹</button><button class="produto-card__nav produto-card__nav--proxima" type="button" aria-label="Próxima imagem">›</button><span class="produto-card__indicadores">${imgs.map((_,i)=>`<i class="produto-card__indicador ${i?'':'ativo'}"></i>`).join('')}</span>`:'';const meta=[p.preco?`<strong class="produto-card__preco">${esc(p.preco)}</strong>`:'',p.prazo?`<span>Encomende com ${esc(p.prazo)}</span>`:''].join('');return `<article class="produto-card"><div class="produto-card__img-wrap" data-carrossel>${slides}${nav}${p.destaque?'<span class="produto-card__badge">Mais pedido</span>':''}</div><div class="produto-card__body"><h3 class="produto-card__nome">${nome}</h3><p class="produto-card__desc">${esc(p.descricao||'')}</p>${meta?`<div class="produto-card__meta">${meta}</div>`:''}<div class="produto-card__footer"><span class="produto-card__cat">${esc(p.categoria||'')}</span><a class="produto-card__cta" href="${whats(p)}" target="_blank" rel="noopener">Pedir este produto</a></div></div></article>`;}
function iniciarCarrossel(el){const slides=[...el.querySelectorAll('.produto-card__slide')];let atual=0;const trocar=i=>{atual=(i+slides.length)%slides.length;slides.forEach((s,n)=>s.classList.toggle('ativa',n===atual));el.querySelectorAll('.produto-card__indicador').forEach((d,n)=>d.classList.toggle('ativo',n===atual));};el.querySelector('.produto-card__nav--anterior')?.addEventListener('click',e=>{e.stopPropagation();trocar(atual-1);});el.querySelector('.produto-card__nav--proxima')?.addEventListener('click',e=>{e.stopPropagation();trocar(atual+1);});el.addEventListener('click',e=>{if(!e.target.closest('button'))abrir(slides.map(s=>s.src),atual,slides[atual].alt);});}
function abrir(urls,indice,nome){galeria=urls;imagemAtual=indice;lbImg.alt=nome;mostrarImagem(indice);lightbox.classList.add('aberto');document.body.style.overflow='hidden';}function mostrarImagem(i){if(!galeria.length)return;imagemAtual=(i+galeria.length)%galeria.length;lbImg.src=galeria[imagemAtual];lbCount.textContent=galeria.length>1?`${imagemAtual+1} de ${galeria.length}`:'';lbPrev.hidden=lbNext.hidden=galeria.length<2;}function fechar(){lightbox?.classList.remove('aberto');document.body.style.overflow='';}function imagens(p){return(Array.isArray(p.imagensUrls)?p.imagensUrls:[p.imagemUrl]).filter(x=>typeof x==='string'&&x);}function whats(p){const extra=[p.preco&&`Preço: ${p.preco}`,p.prazo&&`Prazo: ${p.prazo}`].filter(Boolean).join(' | ');return `https://wa.me/${WPP_NUMBER}?text=${encodeURIComponent(`Olá! Gostaria de pedir: ${p.nome}${extra?` (${extra})`:''} 🍰`)}`;}function esc(v=''){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
